package com.heyuo.qy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConsultRecords<M extends BaseConsultRecords<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setFromUser(java.lang.String fromUser) {
		set("from_user", fromUser);
	}

	public java.lang.String getFromUser() {
		return get("from_user");
	}

	public void setToUser(java.lang.String toUser) {
		set("to_user", toUser);
	}

	public java.lang.String getToUser() {
		return get("to_user");
	}

	public void setDate(java.util.Date date) {
		set("date", date);
	}

	public java.util.Date getDate() {
		return get("date");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setForbidden(java.lang.Boolean forbidden) {
		set("forbidden", forbidden);
	}

	public java.lang.Boolean getForbidden() {
		return get("forbidden");
	}

	public void setSendSuccess(java.lang.Boolean sendSuccess) {
		set("send_success", sendSuccess);
	}

	public java.lang.Boolean getSendSuccess() {
		return get("send_success");
	}

	public void setMsgId(java.lang.String msgId) {
		set("msg_id", msgId);
	}

	public java.lang.String getMsgId() {
		return get("msg_id");
	}

	public void setCrawl(java.lang.Boolean crawl) {
		set("crawl", crawl);
	}

	public java.lang.Boolean getCrawl() {
		return get("crawl");
	}

	public void setCrawlErrorMsg(java.lang.String crawlErrorMsg) {
		set("crawl_error_msg", crawlErrorMsg);
	}

	public java.lang.String getCrawlErrorMsg() {
		return get("crawl_error_msg");
	}

	public void setFromUserKf(java.lang.Boolean fromUserKf) {
		set("from_user_kf", fromUserKf);
	}

	public java.lang.Boolean getFromUserKf() {
		return get("from_user_kf");
	}

}
