package com.heyuo.qy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQyLevel<M extends BaseQyLevel<M>> extends Model<M> implements IBean {

	public void setQy(java.lang.String qy) {
		set("qy", qy);
	}

	public java.lang.String getQy() {
		return get("qy");
	}

	public void setWxUser(java.lang.String wxUser) {
		set("wx_user", wxUser);
	}

	public java.lang.String getWxUser() {
		return get("wx_user");
	}

	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}

	public java.lang.Integer getLevel() {
		return get("level");
	}

}
