package com.heyuo.qy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMsgMedia<M extends BaseMsgMedia<M>> extends Model<M> implements IBean {

	public void setMsgId(java.lang.String msgId) {
		set("msg_id", msgId);
	}

	public java.lang.String getMsgId() {
		return get("msg_id");
	}

	public void setFilePath(java.lang.String filePath) {
		set("file_path", filePath);
	}

	public java.lang.String getFilePath() {
		return get("file_path");
	}

	public void setUrlPath(java.lang.String urlPath) {
		set("url_path", urlPath);
	}

	public java.lang.String getUrlPath() {
		return get("url_path");
	}

}
