package com.heyuo.qy.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("consult_records", "id", ConsultRecords.class);
		arp.addMapping("msg_media", "id", MsgMedia.class);
		arp.addMapping("qy_level", "wx_user", QyLevel.class);
	}
}

