package com.heyuo.qy.model;

import com.heyuo.qy.model.base.BaseConsultRecords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ConsultRecords extends BaseConsultRecords<ConsultRecords> {
	public static final ConsultRecords dao = new ConsultRecords();
}
