package com.heyuo.qy.model;

import com.heyuo.qy.model.base.BaseMsgMedia;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MsgMedia extends BaseMsgMedia<MsgMedia> {
	public static final MsgMedia dao = new MsgMedia();
}
