package com.heyuo.qy.model;

import com.heyuo.qy.model.base.BaseQyLevel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QyLevel extends BaseQyLevel<QyLevel> {
	public static final QyLevel dao = new QyLevel();
}
